from crewai import Agent,LLM
from dotenv import load_dotenv
import os
from tools import location
load_dotenv()
# Retrieve the API key
api_key = os.getenv("OPENAI_API_KEY")
gem_api_key = os.getenv("GEMINI_API_KEY")

llm = LLM(model="groq/llama3-8b-8192",api_key=api_key)
llm1 = LLM(model="gemini/gemini-1.5-flash", temperature=0.7, api_key=gem_api_key)

activity_finder=Agent(
    role="Outdoor Activity Finder",
    goal=("Suggest outdoor activites based to do at a nearby location to {location}, based on the following requirements"
    "Type of activity {category}, and time required to do the activity {time}"),
    backstory="Creative and Smart, you suggest most simple and playful outdoor activities to help people tackle boredom",
    verbose=True,
    allow_delegation=False,
    tools=[location,],
    llm=llm1
)

activity_moderator=Agent(
    role="Outdoor Activity Moderator",
    goal=("Pick the best outoor activity for the user based on the suggestions provided by the Outdoor Activity Finder"
    "The activity should fall under the category of {category}, and could be finished under the time of {time}"),
    backstory="As the head of a Game Company, you're Creative and Smart, you suggest most simple and playful outdoor activities to help people tackle boredom",
    verbose=True,
    allow_delegation=False,
    # tools=[location,],
    llm=llm
)
quest_creator = Agent(
    role="Quest Creator",
    goal=(
        "Generate a multi-step quest with activities near location {location} based on the theme {category} and time limit of {time}. "
        "The quest should include a series of 3-5 activities that are fun and interactive."
    ),
    backstory=(
        "As an expert quest designer, you craft fun and engaging quests based on themes like 'Adventure', 'Mystery', etc. "
        "Your quests have a balanced structure with 3-5 steps that users will enjoy completing."
    ),
    verbose=True,
    allow_delegation=False,
    tools=[location],
    llm=llm1
)

quest_moderator = Agent(
    role="Quest Moderator",
    goal=(
        "Review and moderate the quest generated by the Quest Creator. Ensure that the quest activities align with the user's "
        "preferences in terms of category, time, and location. Make sure the combined time of quest does not exceed the time constrain."
    ),
    backstory=(
        "As a Quest moderator, you ensure that the quests are fun, balanced, and meet user preferences. You will moderate and "
        "adjust the quest to ensure that each activity fits within the user's time constraints and difficulty preferences."
    ),
    verbose=True,
    allow_delegation=False,
    tools=[location],
    llm=llm1
)
