from crewai import Task
from agents import activity_finder,activity_moderator, quest_creator, quest_moderator
from tools import location

activity_finder_task = Task(
    description=(
        "Suggest a series of outdoor activities near the location {location}. "
        "The activity should fall under the category of {category}, and the estimated time required should be {time}. "
        "You should aim to provide engaging, creative, and fun activities that can break the user’s routine and introduce a bit of spontaneity into their day. "
        "The suggestions should be simple, practical, and playful, catering to the user’s context and preferences."
    ),
    expected_output=(
        "A list of three suggested outdoor activities that meet the user's preferences, "
        "including the category, time constraints, and location. "
        "Each activity should be accompanied by a brief description and estimated time. "
        "Ensure the activities are playful and fit within the user’s time availability."
    ),
    tools=[location],
    agent=activity_finder
)

activity_moderator_task = Task(
    description=(
        "Review and select the best outdoor activity from the suggestions provided by the activity_finder agent. "
        "Ensure the activity fits within the location {location}, the category {category}, and can be completed in {time}. "
        "Pick the most suitable activity based on relevance and engagement for the user. "
        "Provide the user with a concise and actionable recommendation, along with any helpful tips or additional information to enhance the experience."
    ),
    expected_output=(
        "A single, recommended outdoor activity that best matches the user's preferences, including location, category, and time. "
        "The recommendation should be clear, easy to follow, and informative. "
        "Include any relevant tips or suggestions to make the activity more enjoyable."
    ),
    # tools=[location],
    agent=activity_moderator
)

quest_creator_task = Task(
    description=(
        "Create a multi-step quest for the user at location {location} based on the theme {category} and time duration of {time}. "
        "The quest should consist of 3-5 engaging and interactive activities, considering the user’s interests and preferences. "
        "Each activity should be related to the theme and fit within the difficulty level. "
        "Provide a clear sequence of activities with brief descriptions and estimated times to complete each one."
    ),
    expected_output=(
        "A list of 3-5 activities that form a coherent quest. "
        "Each activity should include a description, time estimates, and should align with the user’s theme and difficulty preferences. "
        "The quest should be playful, engaging, and easy to follow, with a balance of challenges suitable for the user’s level."
    ),
    tools=[location],
    agent=quest_creator
)

quest_moderator_task = Task(
    description=(
        "Review and moderate the multi-step quest generated by the Quest Creator agent. "
        "Ensure the quest meets the user’s preferences in terms of theme, location, and time constraints. "
        "Make sure each activity fits well within the given difficulty and time frame, and suggest any modifications if necessary. "
        "Provide a final quest recommendation that includes 3-5 activities, ensuring they are both engaging and achievable."
    ),
    expected_output=(
        "A single, final quest recommendation that is well-balanced and suitable for the user’s theme, location, and time preferences. "
        "Each activity should be adjusted to fit within the constraints, with the final quest being easy to follow, fun, and rewarding. "
        "Any tips or additional recommendations to improve the user’s experience should be included."
    ),
    agent=quest_moderator
)

